In [14]:
import numpy as np


p = np.poly1d([1,2,3,-4])
pol = np.poly1d([1,2,3], True, variable = 'z') # Construye el polinomio de raices 1 2 3

print('Polinomio p\n', p)
print('Polinomio pol\n', pol)

print(pol[0]) # coeficiente de potencia 0

print(np.asarray(pol)) # array de coeficientes del polinomio
print(np.square(pol)) # array de coeficientes al cuadrado

print('Raices de pol \n', pol.r) # raices del polinomio

d = pol.deriv(); d = np.polyder(pol) # dos formas de derivar el polinomio
## np.polyder(pol, m) indica el orden de la derivada (m)

dd = np.polyder(pol, 2) # etc

Polinomio p
    3     2
1 x + 2 x + 3 x - 4
Polinomio pol
    3     2
1 z - 6 z + 11 z - 6
-6.0
[ 1. -6. 11. -6.]
[  1.  36. 121.  36.]
Raices de pol 
 [3. 2. 1.]


# Ejercicios de polinomios

In [18]:
# Ejercicio 1

import numpy as np

p1 = np.poly1d([1,-5,10,-12])
p2 = np.poly1d([1,-5,4])

p = p1 + p2

print(p)

   3     2
1 x - 4 x + 5 x - 8


In [19]:
# Ejercicio 2

import numpy as np

p1 = np.poly1d([1,-5,10,-12])
p2 = np.poly1d([1,-4,5,8])

p = p1 - p2

print(p)

    2
-1 x + 5 x - 20


In [20]:
# Ejercicio 3

import numpy as np

p1 = np.poly1d([1,-5,10,-12])
p2 = np.poly1d([1,-5,4])

p = p1 * p2

print(p)

   5      4      3      2
1 x - 10 x + 39 x - 82 x + 100 x - 48


In [21]:
# Ejercicio 4

import numpy as np

p1 = np.poly1d([1,-1,3,-1,1])
p2 = np.poly1d([1,-1,1])

p = p1/p2

print(p)

(poly1d([1., 0., 2.]), poly1d([ 1., -1.]))


In [ ]:
# Ejercicio 5

import numpy as np

p = np.poly1d([3,-3,-2])

dp = np.polyder(p)

x0 = -1

print(dp(x0))

-9


In [ ]:
# Ejercicio 6

import numpy as np

p = np.poly1d([3,-3,-2])

I = np.polyint(p,k=5)

print(I)


   3       2
1 x - 1.5 x - 2 x + 5


'$x=2$'